
graph TD
    subgraph Full Organization Boundary

    style Full Organization Boundary stroke:black
        subgraph Commercial Org Boundary
        direction TB
        style Commercial Org Boundary stroke:blue
            subgraph Commercial Accounts
            direction TB
            style Commercial Accounts stroke:orange
                CustomerAccess[Customer Access Account]
                MonitoringLogging[Monitoring and Logging Account]
                CNAP[CNAP Account]
                style CustomerAccess stroke:orange
                style MonitoringLogging stroke:orange
                style CNAP stroke:orange

                subgraph CustomerAccessDetails
                direction TB
                ALB[ALB]
                CloudFront[CloudFront CDN]
                NetworkFirewall[AWS Network Firewall]
                WAF[AWS WAF]
                Route53[Route 53 DNS]
                style ALB stroke:orange
                style CloudFront stroke:orange
                style NetworkFirewall stroke:orange
                style WAF stroke:orange
                style Route53 stroke:orange
                end
            end
        end

        subgraph GovCloud Org Boundary
        direction TB
        style GovCloud Org Boundary stroke:red
            subgraph USGovWestRegion
            direction TB
            style USGovWestRegion stroke:magenta

                subgraph PrimaryAccount
                direction TB
                style PrimaryAccount stroke:blue

                    subgraph ProdVPC
                    direction TB
                    style ProdVPC stroke:black

                        subgraph AZA_Prod
                        direction TB
                        style AZA_Prod stroke:purple
                        PublicSubnet_AZ_A_Prod[Public Subnet]
                        PrivateSubnet_AZ_A_Prod[Private Subnet]
                        style PublicSubnet_AZ_A_Prod stroke:grey
                        style PrivateSubnet_AZ_A_Prod stroke:grey
                        end

                        subgraph AZB_Prod
                        direction TB
                        style AZB_Prod stroke:purple
                        PublicSubnet_AZ_B_Prod[Public Subnet]
                        PrivateSubnet_AZ_B_Prod[Private Subnet]
                        style PublicSubnet_AZ_B_Prod stroke:grey
                        style PrivateSubnet_AZ_B_Prod stroke:grey
                        end
                    end

                    subgraph StagingVPC
                    direction TB
                    style StagingVPC stroke:black

                        subgraph AZA_Staging
                        direction TB
                        style AZA_Staging stroke:purple
                        PublicSubnet_AZ_A_Staging[Public Subnet]
                        PrivateSubnet_AZ_A_Staging[Private Subnet]
                        style PublicSubnet_AZ_A_Staging stroke:grey
                        style PrivateSubnet_AZ_A_Staging stroke:grey
                        end

                        subgraph AZB_Staging
                        direction TB
                        style AZB_Staging stroke:purple
                        PublicSubnet_AZ_B_Staging[Public Subnet]
                        PrivateSubnet_AZ_B_Staging[Private Subnet]
                        style PublicSubnet_AZ_B_Staging stroke:grey
                        style PrivateSubnet_AZ_B_Staging stroke:grey
                        end
                    end

                    subgraph DevelopmentVPC
                    direction TB
                    style DevelopmentVPC stroke:black

                        subgraph AZA_Dev
                        direction TB
                        style AZA_Dev stroke:purple
                        PublicSubnet_AZ_A_Dev[Public Subnet]
                        PrivateSubnet_AZ_A_Dev[Private Subnet]
                        style PublicSubnet_AZ_A_Dev stroke:grey
                        style PrivateSubnet_AZ_A_Dev stroke:grey
                        end

                        subgraph AZB_Dev
                        direction TB
                        style AZB_Dev stroke:purple
                        PublicSubnet_AZ_B_Dev[Public Subnet]
                        PrivateSubnet_AZ_B_Dev[Private Subnet]
                        style PublicSubnet_AZ_B_Dev stroke:grey
                        style PrivateSubnet_AZ_B_Dev stroke:grey
                        end
                    end

                    subgraph ToolingVPC
                    direction TB
                    style ToolingVPC stroke:black
                    ALB_Privileged[ALB for Privileged Users]
                    BOSH_Director[BOSH Director]
                    UAA[UAA]
                    style ALB_Privileged stroke:black
                    style BOSH_Director stroke:black
                    style UAA stroke:black
                    end

                    subgraph DisasterRecoveryVPC
                    direction TB
                    style DisasterRecoveryVPC stroke:black
                    RDS_Copy[RDS Copy]
                    S3_Copy[S3 Copy]
                    style RDS_Copy stroke:black
                    style S3_Copy stroke:black
                    end
                end

                MonitoringLoggingAccount[Monitoring and Logging Account]
                AWSControlTower[AWS Control Tower]
                SecurityHub[Security Hub]
                style MonitoringLoggingAccount stroke:blue
                style AWSControlTower stroke:blue
                style SecurityHub stroke:blue
            end
        end
    end
